[mysql]
username = "root"
password = "alphamysql"
dbname = "blog"
host = "localhost:3306"
charset = "utf8mb4"
max-idle-conns = 10
max-open-conns = 100

[local]
bloghome = "./blog/"
markdown-path = "/markdown"
topimg-path = "/topImg"

[jwt]
secret = "balabalabala"
expire-time = 604800

[default-user]
username = "alpha"
password = "balabalabala"
