# 这是config.toml的示例文件，如果需要使用，请重命名为config.toml。

# 数据分布
#
# ./data: 数据目录
# ./data/blogs: 博客目录
# ./data/blog-name/markdown: 博客的 markdown 文件
# ./data/blog-name/topimg: 博客的顶部图片
#
# ./data/user: 管理员目录
# ./data/user/admin-avatar: 管理员头像

[local]
# 监听选项
listening-addr = "localhost:3090"

[jwt]
# 运行 'ssh-keygen -t rsa -b 2048 -m PKCS8 -f jwtRS256.key' 获得私钥
private-key = "./jwtRS256.key"
# 运行 'ssh-keygen -e -m PKCS8 -f jwtRS256.key > jwtRS256.key.pub' 获得PKCS8格式的公钥
public-key = "./jwtRS256.key.pub"
# jwt 过期时间，单位：秒
expire-time = 604800

[default-user]
# 管理员的用户名，用于登录后台增删改查博客
username = "yourAdminUsername"
# 管理员密码
password = "yourAdminPassword"
